v1.0.0-alpha.0 (#28)
* Full rewrite; consolidate to one node; Multiple devices allowed

* Rm unused file

* Connection fixes

* More fixes

* Fix docs

* fix/change README wording

* set version 1.0.0-alpha.0

* Bug fix for device init (#26)

Fixes error "TypeError: node.newDevice is not a function" that occurs when trying to initialize the node with device.

* Changelog updated / switch back to TCP (#27)

* Bug fix for device init

Fixes error "TypeError: node.newDevice is not a function" that occurs when trying to initialize the node with device.

* Minor fixes, Changelog updated

* rename node to kasa

* update node file names

Authored-by: hufftheweevil <jhalbsgut@gmail.com>